### ISSUE TITLE
Website Privacy Error (www.pyvibe.com)

### ISSUE THREAD

**Issue by Aryaman73** [pycob/pyvibe#3]
Seems like the HTTPS cert for the website is having issues 👀
 
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/53343807/227057900-7f96ffe8-2f34-48f8-ae70-32046d73dec5.png">

(MacOS, Chrome)

**Comment by zainhoda** [comment]
Weird -- the site is hosted on GitHub Pages. I can't re-produce. Is this still happening for you?

**Comment by Aryaman73** [comment]
It’s working for me now - could’ve been something on my end, perhaps?
