### ISSUE TITLE
Make login button optional

### ISSUE THREAD

**Issue by ancker010** [pycob/pyvibe#5]
Please provide a mechanism to remove the login button in the navbar.

**Comment by zainhoda** [comment]
That's a great idea! In the meantime, what you can do is copy the production `Navbar` and then remove the button from the `to_html()`

https://github.com/pycob/pyvibe/blob/main/src/pyvibe/__init__.py#L1605-L1664

So you'd make your own `CustomNavbar` class and then when you initialize a Page, do this

`page = cob.Page(navbar = CustomNavbar(...))`

**Comment by ancker010** [comment]
Thanks, I've done that for now. Hopefully there's a more elegant method in the future.

**Comment by zainhoda** [comment]
For now I've removed the login button
